name: hotspot_host_questionnaire
description: Onboarding Questionnaire for Hotspot Hosts

publish_to: 'none'

version: 1.0.0+1

environment:
#  sdk: '>=3.0.0 <4.0.0'
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  dio: ^5.3.2
  cached_network_image: ^3.3.0
  audioplayers: ^5.2.1
  camera: ^0.10.5
  video_player: ^2.8.2
  permission_handler: ^11.0.1
  image: ^4.0.17
  record: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/